### ISSUE TITLE
Show some message when insert is still in progress 

### ISSUE THREAD

**Issue by jaelgu** [milvus-io/milvus_cli#34]
There is no message after csv file is processed & before insert is done:
<img width="399" alt="Screen Shot 2021-09-06 at 3 19 57 PM" src="https://user-images.githubusercontent.com/86251631/132176454-41f0e9bf-d208-4878-bf42-ddbf69d7adc4.png">

When it takes long time to insert, it is confusing.

**Comment by czhen-zilliz** [comment]
![image](https://user-images.githubusercontent.com/83751452/132463097-985380dd-01f3-4eab-8a75-fddfa0c6d836.png)
