### ISSUE TITLE
Query failed on loaded collection

### ISSUE THREAD

**Issue by nameczz** [milvus-io/milvus_cli#52]
1. connect milvus
2. query on already loaded collection
3. throw Error: <BaseException: (code=5, message=collection has already been loaded, and the number of replicas 1 is not same as the request's 0. Should release first then reload with the new number of replicas)>

query on unloaded collection, every working fine.

**Comment by shanghaikid** [comment]
milvus version ?

**Comment by nameczz** [comment]
will create issue under zillizTech
